/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/Settings/index'
import { Route as SetQuizDifficultyViewIndexRouteImport } from './routes/SetQuizDifficultyView/index'
import { Route as ReportIndexRouteImport } from './routes/Report/index'
import { Route as ProfileIndexRouteImport } from './routes/Profile/index'
import { Route as LeaderboardIndexRouteImport } from './routes/Leaderboard/index'
import { Route as EndOfQuizIndexRouteImport } from './routes/EndOfQuiz/index'
import { Route as QuizSubjectIdTopicIdIndexRouteImport } from './routes/quiz/$subjectId/$topicId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/Settings/',
  path: '/Settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetQuizDifficultyViewIndexRoute =
  SetQuizDifficultyViewIndexRouteImport.update({
    id: '/SetQuizDifficultyView/',
    path: '/SetQuizDifficultyView/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/Report/',
  path: '/Report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/Profile/',
  path: '/Profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/Leaderboard/',
  path: '/Leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndOfQuizIndexRoute = EndOfQuizIndexRouteImport.update({
  id: '/EndOfQuiz/',
  path: '/EndOfQuiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSubjectIdTopicIdIndexRoute =
  QuizSubjectIdTopicIdIndexRouteImport.update({
    id: '/quiz/$subjectId/$topicId/',
    path: '/quiz/$subjectId/$topicId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/EndOfQuiz/': typeof EndOfQuizIndexRoute
  '/Leaderboard/': typeof LeaderboardIndexRoute
  '/Profile/': typeof ProfileIndexRoute
  '/Report/': typeof ReportIndexRoute
  '/SetQuizDifficultyView/': typeof SetQuizDifficultyViewIndexRoute
  '/Settings/': typeof SettingsIndexRoute
  '/quiz/$subjectId/$topicId/': typeof QuizSubjectIdTopicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/EndOfQuiz': typeof EndOfQuizIndexRoute
  '/Leaderboard': typeof LeaderboardIndexRoute
  '/Profile': typeof ProfileIndexRoute
  '/Report': typeof ReportIndexRoute
  '/SetQuizDifficultyView': typeof SetQuizDifficultyViewIndexRoute
  '/Settings': typeof SettingsIndexRoute
  '/quiz/$subjectId/$topicId': typeof QuizSubjectIdTopicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/EndOfQuiz/': typeof EndOfQuizIndexRoute
  '/Leaderboard/': typeof LeaderboardIndexRoute
  '/Profile/': typeof ProfileIndexRoute
  '/Report/': typeof ReportIndexRoute
  '/SetQuizDifficultyView/': typeof SetQuizDifficultyViewIndexRoute
  '/Settings/': typeof SettingsIndexRoute
  '/quiz/$subjectId/$topicId/': typeof QuizSubjectIdTopicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/EndOfQuiz/'
    | '/Leaderboard/'
    | '/Profile/'
    | '/Report/'
    | '/SetQuizDifficultyView/'
    | '/Settings/'
    | '/quiz/$subjectId/$topicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/EndOfQuiz'
    | '/Leaderboard'
    | '/Profile'
    | '/Report'
    | '/SetQuizDifficultyView'
    | '/Settings'
    | '/quiz/$subjectId/$topicId'
  id:
    | '__root__'
    | '/'
    | '/EndOfQuiz/'
    | '/Leaderboard/'
    | '/Profile/'
    | '/Report/'
    | '/SetQuizDifficultyView/'
    | '/Settings/'
    | '/quiz/$subjectId/$topicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndOfQuizIndexRoute: typeof EndOfQuizIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ReportIndexRoute: typeof ReportIndexRoute
  SetQuizDifficultyViewIndexRoute: typeof SetQuizDifficultyViewIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  QuizSubjectIdTopicIdIndexRoute: typeof QuizSubjectIdTopicIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Settings/': {
      id: '/Settings/'
      path: '/Settings'
      fullPath: '/Settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SetQuizDifficultyView/': {
      id: '/SetQuizDifficultyView/'
      path: '/SetQuizDifficultyView'
      fullPath: '/SetQuizDifficultyView/'
      preLoaderRoute: typeof SetQuizDifficultyViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Report/': {
      id: '/Report/'
      path: '/Report'
      fullPath: '/Report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Profile/': {
      id: '/Profile/'
      path: '/Profile'
      fullPath: '/Profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Leaderboard/': {
      id: '/Leaderboard/'
      path: '/Leaderboard'
      fullPath: '/Leaderboard/'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/EndOfQuiz/': {
      id: '/EndOfQuiz/'
      path: '/EndOfQuiz'
      fullPath: '/EndOfQuiz/'
      preLoaderRoute: typeof EndOfQuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$subjectId/$topicId/': {
      id: '/quiz/$subjectId/$topicId/'
      path: '/quiz/$subjectId/$topicId'
      fullPath: '/quiz/$subjectId/$topicId/'
      preLoaderRoute: typeof QuizSubjectIdTopicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndOfQuizIndexRoute: EndOfQuizIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ReportIndexRoute: ReportIndexRoute,
  SetQuizDifficultyViewIndexRoute: SetQuizDifficultyViewIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  QuizSubjectIdTopicIdIndexRoute: QuizSubjectIdTopicIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
